### ISSUE TITLE
get emulation screenshot

### ISSUE THREAD

**Issue by dimabubenok** [BinBashBanana/webretro#1]
Hi! Is there any way to get the result of calling _Module._cmd_take_screenshot()_ method?

**Comment by BinBashBanana** [comment]
That seems like a good idea to implement in the future! Should I have the screenshot immediately downloaded? Or did you have something else in mind?

**Comment by BinBashBanana** [comment]
You may have to put it on a short setTimeout.

**Comment by dimabubenok** [comment]
I did save screenshot to file:
`function takeScreenshot(){
	Module._cmd_take_screenshot();
	var screenshot_path = "/home/web_user/retroarch/userdata/screenshots/";
	var screenshot_name = makeScreenshotFilename();

	window.setTimeout(function() {
		if(FS.analyzePath(screenshot_path+screenshot_name).exists) {
			var file = FS.readFile(screenshot_path+screenshot_name);
			downloadFile(file,screenshot_name);
		} else {
			console.log('screenshot not found')
		}
	}, 500);
}

function makeScreenshotFilename(){
	var now = new Date();
	var y = now.getFullYear().toString().slice(-2),
		m = ("0" + (now.getMonth() + 1)).slice(-2),
		d = ("0" + now.getDate()).slice(-2),
		h = ("0" + now.getHours()).slice(-2),
		i = ("0" + now.getMinutes()).slice(-2),
		s = ("0" + now.getSeconds()).slice(-2);

	return `rom-${y}${m}${d}-${h}${i}${s}.png`;
}`

**Comment by BinBashBanana** [comment]
Nice! That works very well! I was planning on making a screenshot gallery feature, so that the user could browse their screenshots, and then download them whenever they want. Will be in the next update.
