### ISSUE TITLE
Functionality Issues

### ISSUE THREAD

**Issue by sproutonion** [BinBashBanana/webretro#104]
I was playing Wario Woods and the game started to lag signficantly (the music and game). Yes, it's playable, but barely. Everything was working fine up until round 55. I saved, reset, reloaded, closed the tab and reopened it, but it continues to stay at this buggy state. Is there a fix that won't wipe my save data?

**Comment by BinBashBanana** [comment]
Is this the NES or SNES version?

**Comment by sproutonion** [comment]
NES version, but my issue was just resolved. It was a problem on my end. My computer was low on battery. Thank you! I really enjoy this emulator.

**Comment by BinBashBanana** [comment]
Oh lol. Thank you
