### ISSUE TITLE
Suggestion: Allow multiple people to connect to a singular instance

### ISSUE THREAD

**Issue by KoNickss** [BinBashBanana/webretro#109]
You could generate shareable session IDs for people to connect to the same instance and then accomplish basically a hassle, de-sync, and lag free netplay service, this would be truly revolutionary as current methods of netplay require complicated setups, perfect matching (same rom, save file, emultor version) and often insane bandwith, while still often desyncing and or suffering from heavy lag. Something like this would go a long way for making netplay usable, I may also be able to help and would like to, this project is really really cool and I would love to see it get even better!

**Comment by BinBashBanana** [comment]
This would quickly become more complicated than regular netplay, and it would also require a server to manage it. That is not the goal of this project. Perhaps something like [retrobot](https://github.com/rossimo/retrobot) may already satisfy your needs, or it may be a fitting feature for [gaseous](https://github.com/gaseous-project/gaseous-server).

**Comment by KoNickss** [comment]
Oh yup my bad, upon further research it seems like the game is rendered client side, thought the client simply streamed input and audio video from the server, which wouldve indeed made this easy. But as it is I stand corrected, this would indeed be a pain in the ass. Thank you for the quick and concise reply tho, really love the project!
