### ISSUE TITLE
broken shaders

### ISSUE THREAD

**Issue by ethanaobrien** [BinBashBanana/webretro#11]
It seems the commit `65ab91cfc5db110d3236ac8b6148e7e935b46d18` [(link](https://github.com/BinBashBanana/webretro/commit/65ab91cfc5db110d3236ac8b6148e7e935b46d18)) broke some shaders for the n64.

I tried running mario kart 64, It seemed to run fine until it had to render the level screen and it seemed that the entire UI just crashed, nothing would render. I backtracked to see what broke it and it was in this commit. It worked in the commit before this (last working commit - `526f18b06058a68b405488549773fe47ebf4af61` [(link)](https://github.com/BinBashBanana/webretro/commit/526f18b06058a68b405488549773fe47ebf4af61)

I tested using githack: https://raw.githack.com/BinBashBanana/webretro/526f18b06058a68b405488549773fe47ebf4af61/index.html?core=mupen64plus_next

I ran some testing - `webgl2` did not break this

**Comment by BinBashBanana** [comment]
Interesting... this error does not occur on my local server, or on githack, but it does on github.io. I have no idea what is causing this lol

**Comment by BinBashBanana** [comment]
This should be fixed now with the 6.5 update.
