### ISSUE TITLE
GB/GBC/GBA - Pokemon Emerald Problem

### ISSUE THREAD

**Issue by Gygrfynhvfcddeft** [BinBashBanana/webretro#110]
I am trying to load Pokemon Emerald but it just says "Loading, Waiting For Emulator" forever and never loads. I have a 10-hour save file in there but I need the emulator to get it.

**Comment by BinBashBanana** [comment]
Please send console output

**Comment by Gygrfynhvfcddeft** [comment]
Got core: mgba
WASM ready
Starting bundle fetch
Finished bundle fetch in 1.8 seconds, 0 errors
Succesfully read ROM file "Pokemon - Emerald Version (U).gba"
Initializing with 16.00 MiB of data

**Comment by BinBashBanana** [comment]
Copy from the devtools console instead

**Comment by Gygrfynhvfcddeft** [comment]
where is that? cant find it.

**Comment by ethanaobrien** [comment]
https://www.google.com/search?q=how%20to%20open%20devtools%20console

**Comment by Gygrfynhvfcddeft** [comment]
its gray and cant use it

**Comment by Gygrfynhvfcddeft** [comment]
nvm i started a new save file 3 days ago and I beat it
