### ISSUE TITLE
Running offline

### ISSUE THREAD

**Issue by FieryMewtwo** [BinBashBanana/webretro#12]
When run locally, webretro just hangs on the "Loading" screen. Do you (@BinBashBanana) know what might be wrong?

**Comment by ethanaobrien** [comment]
Are you opening the file? Does the URL show `file` at the top? Could you copy and paste the link?

**Comment by BinBashBanana** [comment]
@FieryMewtwo You can't use `file://` urls, you will have to use something like python's built-in http server: `python3 -m http.server`

**Comment by FieryMewtwo** [comment]
Okay. Thanks!

**Comment by FieryMewtwo** [comment]
> 

yeah, I see my issue now... thanks for the info though and the help!
