### ISSUE TITLE
DS Emulator

### ISSUE THREAD

**Issue by ZackandHack** [BinBashBanana/webretro#13]
Ok so basically I Love DS games and I was wondering if you can add in your emulator the DS games and while I understand it's laggy, I was wondering if its possible for the DS games to run more faster (I play on Chromebook) and an idea I had was to make it were you can make the frames go higher or lower as an option

**Comment by ZackandHack** [comment]
Also I am a new User

**Comment by BinBashBanana** [comment]
I'm working on a DS core right now :) (using melonDS, as it appears to be better than desmume at least as a libretro core)

**Comment by ZackandHack** [comment]
Great to hear :) but I was wondering if there is a demo you can give me as I could try to test it and see how it goes

**Comment by BinBashBanana** [comment]
I probably won't have a demo set up for a while.

**Comment by ZackandHack** [comment]
Ok thanks for letting me know :D

**Comment by mistertoenails** [comment]
When will this be up, do you think? I want to play some pokemon platinum!

**Comment by BinBashBanana** [comment]
Moving this issue to #15
