### ISSUE TITLE
PS1 Support

### ISSUE THREAD

**Issue by Senshi209** [BinBashBanana/webretro#14]
I was wondering if you could add ps1 support to webretro? Really wanting to play Metal Gear Solid

**Comment by BinBashBanana** [comment]
Yeah I'll see about adding Mednafen PSX

**Comment by Senshi209** [comment]
Ok thx, really appreciate the work youre doing on this project :)

**Comment by BinBashBanana** [comment]
@Senshi209 6.5 is released with Beetle (Mednafen) PSX HW [here](https://binbashbanana.github.io/webretro/?core=mednafen_psx_hw). I worked hard on GLES 3.0 support for HW emulation, see pull [#856](https://github.com/libretro/beetle-psx-libretro/pull/856).
