### ISSUE TITLE
When is the MelonDS Emulator coming to Webretro?

### ISSUE THREAD

**Issue by Cha0t1cDX** [BinBashBanana/webretro#15]
I knew from HU that you were developing a ds emulator for it, so i wanted to know; is melonDS coming out anytime soon?
Thanks!

**Comment by Senshi209** [comment]
https://ds.44670.org/

This works and has saves, tested it with pokemon soulsilver and bowser's inside story. It gets laggy sometimes, but when melonds comes just export your save and play on webretro because melonds is more optimized for the browser making it less laggy.

**Comment by BinBashBanana** [comment]
MelonDS with software rendering (slow) will release in the next release (6.5), I'm planning on learning OpenGL so I can write a GL ES renderer which no DS emulator has. (this will make it much faster) Even with threading, software rendering is slow.

**Comment by Cha0t1cDX** [comment]
ok! thanks for respondin'!

**Comment by BinBashBanana** [comment]
@Cha0t1cDX @ZackandHack 6.5 is released, you can use the melonDS core [here](https://binbashbanana.github.io/webretro/?core=melonds).
