### ISSUE TITLE
Not really an issue but a question.

### ISSUE THREAD

**Issue by WhenIsItBig** [BinBashBanana/webretro#17]
So my school has recently blocked all access to github pages, which means I won't be able to use any sort of github related item. I was wondering if you could download the entire webpage and view it offline? If someone knows how, please tell me. Thank you

**Comment by RuralAnemone** [comment]
holy yikes I'm an idiot I didn't read the repo
lol

but yeah you can still use those, just pretend I said "(github.com/binbashbanana.webretro)[https://github.com/binbashbanana/webretro]"


also in this case personally I'm using replit
[link to deploy](https://replit.com/github/binbashbanana/webretro)

**Comment by RuralAnemone** [comment]
no okay so unfortunately full offline support isn't a thing
![image](https://user-images.githubusercontent.com/64103005/168820542-26111e28-595a-4360-9a38-71ae52da3537.png)

**Comment by BinBashBanana** [comment]
@WhenIsItBig next release I'll make a single html file like eaglercraft has that you can download. It will require internet to work though.

**Comment by WhenIsItBig** [comment]
Alright, thank you! I'll be on the lookout for that.

**Comment by WhenIsItBig** [comment]
About when can I expect the next release to come out?

**Comment by BinBashBanana** [comment]
Early June, probably

**Comment by BinBashBanana** [comment]
Only loading it should require internet (to get the necessary files), once it's loaded, you don't need it.

**Comment by BinBashBanana** [comment]
It's a secret >:D

**Comment by Cha0t1cDX** [comment]
waiting excitedly

**Comment by RuralAnemone** [comment]
ditto :)

**Comment by WhenIsItBig** [comment]
me too

**Comment by BinBashBanana** [comment]
The update will take a little longer because of finals, sorry.

**Comment by WhenIsItBig** [comment]
IM BACK

**Comment by WhenIsItBig** [comment]
when's the next release coming? :)

**Comment by BinBashBanana** [comment]
I ended up working on a bunch of unplanned features / QoL improvements, but I only have 4 short items left on my todo list before release (one of them is to make the standalone HTML file, which should be very simple but it has to be done after almost everything else). It should release on or before this weekend. (This time for real)

**Comment by BinBashBanana** [comment]
@WhenIsItBig @Cha0t1cDX @RuralAnemone released! [6.5](https://github.com/BinBashBanana/webretro/commit/ef0068a19afb0f1a180457683f441575ce46b1f0)

You can get the standalone file [here](https://cdn.jsdelivr.net/gh/BinBashBanana/webretro/utils/webretro-standalone.html).
