### ISSUE TITLE
PS1 emulator texture glitches

### ISSUE THREAD

**Issue by manlycracker65** [BinBashBanana/webretro#24]
some of the textures on the ps1 emulator glitches out, i can post a screenshot of it doing it if you want,

**Comment by manlycracker65** [comment]
![image](https://user-images.githubusercontent.com/103338779/184185048-6efe9453-df59-4659-b710-d0bf5ca30931.png)

**Comment by BinBashBanana** [comment]
Try using the software renderer instead, it usually is more compatible but slower depending on your computer. Before choosing the ROM files, go to More > Pre-start Options > check "Use Software Renderer"

**Comment by manlycracker65** [comment]
where do i find the pre start options?
![image](https://user-images.githubusercontent.com/103338779/184226381-cedb4db9-c43d-48f7-8809-90d64212dc15.png)

**Comment by BinBashBanana** [comment]
You have to go to Beetle PSX first, it's under "More" in the menu at the top.

**Comment by manlycracker65** [comment]
thank you, the issue has been resolved!
