### ISSUE TITLE
will i ever be able to load custom cores?

### ISSUE THREAD

**Issue by zdc54** [BinBashBanana/webretro#3]
is this possible?

**Comment by zdc54** [comment]
and if so, how would i do so? (i am very smol brain, so i am not really sure)

**Comment by BinBashBanana** [comment]
Once you build the core successfully (from https://github.com/libretro) you can put the output files in the same directory as index.html.  
Then load the core with the flag in the url bar `?core=CORENAME`.

Keep in mind that a lot of cores can't be built yet, and that's not my problem.

**Comment by BinBashBanana** [comment]
See #5
