### ISSUE TITLE
Embedding

### ISSUE THREAD

**Issue by Spew45** [BinBashBanana/webretro#33]
I'm trying to embed it, and I can't figure it out. if you can help me because it just shows the 404 error as it can't find the file.

**Comment by BinBashBanana** [comment]
Please give more details. What is giving the 404 error? Are you using the embed script or not?

**Comment by BinBashBanana** [comment]
@Spew45

**Comment by ghost** [comment]
@BinBashBanana i also got some questions about embedding, can you post a tutorial on youtube or something?

**Comment by ghost** [comment]
Because whenever i try to use the embed code it just has the heading that says "Example Embed" and nothing else.

**Comment by BinBashBanana** [comment]
You need to embed the actual webretro page, not embed-example.html

**Comment by ghost** [comment]
oh ok but what if i wanted to embed a specific game

**Comment by ghost** [comment]
@BinBashBanana what if i wanted to do a similar thing that websites like [holy unblocker](https://holyubofficial.net/) do where they embed specific games

**Comment by RuralAnemone** [comment]
> BinBashBanana what if i wanted to do a similar thing that websites like [holy unblocker](https://holyubofficial.net/) do where they embed specific games

@ProbablyKam see https://github.com/BinBashBanana/webretro#how-to-use

**Comment by ghost** [comment]
ok thx
