### ISSUE TITLE
unable to set bios for sega CD emulation

### ISSUE THREAD

**Issue by skunksecond** [BinBashBanana/webretro#35]
Sega CD emulation doesn't work because its impossible (as far as i am aware) to add a Sega CD bios to the Genesis Plus GX core. It's possible to load an image of the Sega CD bios but I can't load the bios image into the core before playing the game. Is there something im missing here?

**Comment by BinBashBanana** [comment]
Sorry for the late response, this is possible in the current version, but you will have to modify the top of `base.js`:
add `"genesis_plus_gx": {path: "", files: ["bios_CD_E.bin", "bios_CD_U.bin", "bios_CD_J.bin"]}` to the `bioses` object
add `"genesis_plus_gx"` to `multiFileCores`, `playlistCores`, and `cdromCores`

This will also be released in v6.6.
