### ISSUE TITLE
Could you possibly add a Gamecube core?

### ISSUE THREAD

**Issue by SubduedCyns** [BinBashBanana/webretro#36]
Hello there BinBashBanana!
 I’m back from the dead and to suggest a core! 
Pokemon Colosseum is really taking the title as the hardest Pokemon spinoff game.
 Not much here to say really.
 Thanks for reading this and I hope you add it in for 6.6 or possibly 6.7. 
-ChaoticDX

**Comment by ethanaobrien** [comment]
Please note #28

**Comment by BinBashBanana** [comment]
Do not count on any GameCube core. (see #28)
