### ISSUE TITLE
Regarding Usage on Chromebook

### ISSUE THREAD

**Issue by HaxsMaster** [BinBashBanana/webretro#37]
Attempting to use the emulators on chromebooks, and even though online versions of the emulators work, downloading the file and using a core from index.hmtl does not work. Any help on this?

**Comment by BinBashBanana** [comment]
You need to use the standalone file, saving index.html will not work. You can download it [here](https://cdn.jsdelivr.net/gh/BinBashBanana/webretro/utils/webretro-standalone.html). (just right click and press save as)
See #17
