### ISSUE TITLE
Stream from the Cloud

### ISSUE THREAD

**Issue by ZackandHack** [BinBashBanana/webretro#38]
I heard that you don't plan on adding 3DS games and while that sucks an idea came up in my head I was wondering if you could stream it by the Cloud and while we're at it could you make an alpha for a 3ds Core and we can test how it runs, 

Btw do you think you can add local or online multiplayer on MelonDS

Thanks for reading this :D

**Comment by BinBashBanana** [comment]
There will never be any cloud streaming in webretro. That would be a different project, and it would require dedicated servers to run the emulators.

Netplay will be added for all supporting cores in v6.7 most likely.

**Comment by ZackandHack** [comment]
Ok thank you
