### ISSUE TITLE
Regarding Loading Pre-Existing Saves

### ISSUE THREAD

**Issue by HaxsMaster** [BinBashBanana/webretro#39]
Would it possible to use pre-existing save files from other emulators? I have a .dsv file and want to import it.

**Comment by BinBashBanana** [comment]
webretro uses melonDS, try using [this tool](https://melonds.kuribo64.net/board/thread.php?pid=825) to convert the save file from .dsv to .sav, then choose the ROM in webretro and import the .sav file by going to "Saves" > "Import SRAM" in the menu bar.

**Comment by HaxsMaster** [comment]
Is there a link for Chromebook?

**Comment by BinBashBanana** [comment]
No
