### ISSUE TITLE
Make a website that's not github.io so people could use it while in school aka i want to use this while in school but they blocked websites using github.io

### ISSUE THREAD

**Issue by Marcelino319** [BinBashBanana/webretro#42]
Not that much of anything really just want to use this while on my school computer please

**Comment by HaxsMaster** [comment]
Go to this issue: https://github.com/BinBashBanana/webretro/issues/37

Right-click the blue "here" link, click save as, and open the consequent file. As its a file, it should be perfectly fine and never be blocked.

@PhDPigeon

**Comment by Marcelino319** [comment]
Thank you @HaxsMaster

**Comment by BinBashBanana** [comment]
thanks again
