### ISSUE TITLE
If possible could you fix the index.html so you can upload files and they actually load the roms

### ISSUE THREAD

**Issue by Marcelino319** [BinBashBanana/webretro#43]
please

**Comment by HaxsMaster** [comment]
You seem have to been doing it incorrectly again. Go to Issue: #37, right-click the blue "Here" link, and use "save as" It should produce: "webretro-standalone.html" I have personally tested it, and it works.

@PhDPigeon

**Comment by Marcelino319** [comment]
oh ok

**Comment by BinBashBanana** [comment]
thanks @HaxsMaster
