### ISSUE TITLE
Regarding Saving Save Data

### ISSUE THREAD

**Issue by HaxsMaster** [BinBashBanana/webretro#46]
How do I adjust the auto-save feature to save more often/save save-data manually?

**Comment by BinBashBanana** [comment]
Currently, it's hardcoded to 300000 ms (5 minutes) but you can search for that number in base.js and change it to whatever you'd like.

To turn off autosave by default, remove `checked` from the input tag [here](https://github.com/BinBashBanana/webretro/blob/ec294546ae4ce540c4704b009c457ced1124b4c2/index.html#L44).
