### ISSUE TITLE
Having problems with my PS1 games.

### ISSUE THREAD

**Issue by George42009** [BinBashBanana/webretro#49]
I downloaded a rom for "Final Fantasy 7" from the site "CDromance" and whenever I upload the directory to webretro, it does not load, however my tekken 2 from for ps1 does load which has a larger file size does load. CDRomance is pretty reliable so it does not seem to be the issue.

**Comment by BinBashBanana** [comment]
I downloaded the same one (assuming the USA one) and it loads fine. Just make sure, if you're loading all 6 files at once, to click one of the "cue" files, not any of the "bin" files.

**Comment by George42009** [comment]
> Reference

So exactly how am I supposed to click specific files, I would open the file but it tells me "Read Only"

**Comment by BinBashBanana** [comment]
I'm very confused as to what you're doing, but here are the steps that should work:
1. Open [Beetle PSX HW](https://binbashbanana.github.io/webretro/?core=mednafen_psx_hw), click "Choose ROM Files", press OK
2. Select the directory where the `.cue` and `.bin` files are located, press OK
3. If it prompts you with "Select the master ROM or playlist", select any of the ".cue" files that show up in the list.
