### ISSUE TITLE
embedding question

### ISSUE THREAD

**Issue by ub03** [BinBashBanana/webretro#50]
you know how in the embed example html file it has a small embed? how do i make it just the game and nothing else?

**Comment by BinBashBanana** [comment]
Please read [this](https://github.com/BinBashBanana/webretro#embedding). You can make and style the container element however you like, and the embed will automatically fill it.

**Comment by ub03** [comment]
do you mind replying with a codebox with the embed example html but just the game and nothing else? i feel like im asking too much but yeah.

**Comment by BinBashBanana** [comment]
In that case, you only need to use the querystring options in the URI, read [here](https://github.com/BinBashBanana/webretro#how-to-use). You can use https://binbashbanana.github.io/webretro or your own instance.

**Comment by ub03** [comment]
OHHHH yeah that makes sense. sorry im a little slow man i really appreciate it
