### ISSUE TITLE
How can I have it run one specific game on one specific webpage?

### ISSUE THREAD

**Issue by CBGamesdev** [BinBashBanana/webretro#51]
I was wondering If i can have this play one specific rom on a specific page without having to select one like JSNES does. If so, walk me through it.

**Comment by RuralAnemone** [comment]
@CBGamesdev try this: https://github.com/BinBashBanana/webretro#how-to-use

**Comment by RuralAnemone** [comment]
see an example: https://3kh0.ruralanemone.tech/projects/webretro/roms.html

**Comment by BinBashBanana** [comment]
Thanks @RuralAnemone
