### ISSUE TITLE
Status Update

### ISSUE THREAD

**Issue by BinBashBanana** [BinBashBanana/webretro#53]
Hello, I have an important announcement. My laptop (under warranty), which I do all my programming on, has been broken for about a week and a half. I have just today sent it to the manufacturer to be repaired. I'll update this when I get it back. Stay tuned!

**Comment by xzcollapse** [comment]
imagine being rich and paying for a warranty. also i hope you have your shit backed up coz they might reset your laptop, depending on what broke. otherwise i wish you well

**Comment by BinBashBanana** [comment]
The laptop was 4 months old, still covered by the minimum warranty. It probably had a defective motherboard or power supply. I didn't back anything up since I got it, but I still have my old laptop with everything on it. Thanks

**Comment by BinBashBanana** [comment]
Ok, I got my laptop back today. Development resumes!
