### ISSUE TITLE
mGBA Loading

### ISSUE THREAD

**Issue by Lonk-lonk-l0nk** [BinBashBanana/webretro#55]
Hey I'm using your service on chrome os and my GBA roms won't load for the life of me. Please fix the issue when you can!
[Screen recording 2022-11-02 10.57.38.webm](https://user-images.githubusercontent.com/117201200/199553760-f4265c36-682b-4613-af94-c89b9ad80882.webm)

**Comment by BinBashBanana** [comment]
I noticed that when you choose the file, it said that it was 0 bytes? That doesn't make any sense but it probably means the file upload is not going through. Try the Google Drive upload button instead.

**Comment by Lonk-lonk-l0nk** [comment]
I just did and it does absolutely nothing to the window

**Comment by BinBashBanana** [comment]
Very strange... Maybe try re-downloading the roms?

**Comment by Lonk-lonk-l0nk** [comment]
I just deleted then re-downloaded all the files and it worked.

**Comment by BinBashBanana** [comment]
Great!

**Comment by RuralAnemone** [comment]
that used to happen to me too - as far as I know it just means that the files didn't sync properly to your drive
