### ISSUE TITLE
theoretical offline standalone webretro

### ISSUE THREAD

**Issue by foxsouns** [BinBashBanana/webretro#59]
it should be possible to dynamically link everything instead of using jsdeliver: i'm working on testing this out now in my own fork. this should allow somebody to just download the repository and open the offline html and run it whenever. would probably require just as much up-keep as the current standalone. i'll make a pull request if i can get it working: this is just an issue made for me to resolve later.

**Comment by foxsouns** [comment]
currently hangs on core load. investigating.

**Comment by foxsouns** [comment]
js is not my strong suit. lol.

**Comment by BinBashBanana** [comment]
See #61

**Comment by foxsouns** [comment]
> See #61

that's my pr, actually
made this issue so that i could have something to solve.

**Comment by BinBashBanana** [comment]
Closing this now, future discussion should happen in #61 or #52.
