### ISSUE TITLE
mGBA Pokemon Fire Red not saving

### ISSUE THREAD

**Issue by skunksecond** [BinBashBanana/webretro#66]
Self explanitory. Pokemon Red on mGBA does not save, instead it gets infinitely stuck on a page with "Save Failed. Checking the backup memory... Please wait. 'Time required: about 1 minute'"

**Comment by BinBashBanana** [comment]
Can you send a screenshot?

**Comment by skunksecond** [comment]
![image](https://user-images.githubusercontent.com/74111880/206906487-fcb31d80-03ad-43f7-9e67-6d1cf550df25.png)

**Comment by BinBashBanana** [comment]
That's very strange, I've never had this issue before. Does this happen all the time?

**Comment by foxsouns** [comment]
This is definitely not Red, but FireRed, for the GBA, right? I could test that one myself and try to recreate it, if nothing else.

**Comment by foxsouns** [comment]
Just tried both revisions of the cart: neither have problems saving in the first room. Where does this problem occur at? Do your cartridge dumps match either of these SHA-1's?

FireRed Rev0: `41cb23d8dccc8ebd7c649cd8fbb58eeace6e2fdc`
FireRed Rev1: `dd5945db9b930750cb39d00c84da8571feebf417`

If you don't know how to generate an SHA-1, just use [this](https://emn178.github.io/online-tools/sha1_checksum.html). If your roms don't match either of these, your file is bad.

**Comment by skunksecond** [comment]
Ah, looks like my file is bad, the checksum is c89b51766c8a8b23332c27dc45a270cea912bc21

**Comment by foxsouns** [comment]
Redump your cart, or "employ other methods". You should know where to look; I am not going to help with the latter.
