### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hrizk07** [BinBashBanana/webretro#73]
Do you know how to play sega cd games? i've been trying to play sonic cd online with the .bin file. But it doesn't work and just leaves me on a black screen.

**Comment by foxsouns** [comment]
don't have the rom to test the game myself, but i'm like, 70% sure that the sega cd roms are in `.iso` format, not `.bin`, because they're just disc back-up images. make sure you have the right file.

**Comment by BinBashBanana** [comment]
@NotGrillface see #35; you'll need to host your own instance for now.
