### ISSUE TITLE
Will you add a xbox 360 core???

### ISSUE THREAD

**Issue by UMBreomn** [BinBashBanana/webretro#93]
i have been wanting to play sonic unleashed but i have only a chromebook so i can't play emulators like Xenia

**Comment by UMBreomn** [comment]
Btw does it support ps2 roms

**Comment by NebulaService** [comment]
Probably not.

As of right now it doesn't support PS2 ISO's

**Comment by foxsouns** [comment]
saw this and:
360 emulation is barely working on _good_ laptop specs. good luck in a chromebook web browser. ps2 emulation is also too powerful for a chromebook. you might be able to run ps1/n64 and behind, but thats pushing physical limits very hard. if i recall correctly, my chromebook would overheat and crash consistently when playing snes games for too long. it is simply not feasible.

**Comment by JMLambo** [comment]
> saw this and: 360 emulation is barely working on _good_ laptop specs. good luck in a chromebook web browser. ps2 emulation is also too powerful for a chromebook. you might be able to run ps1/n64 and behind, but thats pushing physical limits very hard. if i recall correctly, my chromebook would overheat and crash consistently when playing snes games for too long. it is simply not feasible.

It's probably your Chromebook. On mine, I can play snes games just fine, but when it comes to n64 and nds games, My frames go away.
