### ISSUE TITLE
Error 0

### ISSUE THREAD

**Issue by tlochsta** [BinBashBanana/webretro#96]
Unable to reach  https://files.tlochsta.dev/roms/mario_cart_64.zip (error 0)

**Comment by foxsouns** [comment]
1. this is unlawful sharing of copyrighted material
2. that is a you-side issue, as i know [hosting a file](https://github.com/BinBashBanana/webretro/blob/master/embed/embed-example.html) from other hosts work fine. figure what you did wrong in hosting the file, or calling the file, and solve it yourself. this issue should not exist.

**Comment by tlochsta** [comment]
what

**Comment by foxsouns** [comment]
you cant just host the mario 64 rom and leave it publicly dude.
and if you set up a website, debug it yourself 🤷

**Comment by tlochsta** [comment]
"debug it yourself" whatt do u mean
